dbt-labs/actions

- .github/workflows/release.yml
- README.md
- automates creating git tags for PRs after they are merged based on a label on the PR
- maintains the existing release functionality if we want to cut a release without merging a PR (manually creating a git tag)
> update release workflow

- .github/workflows/py-package-info.yml
- py-package-info/main.py
when version is not specified as an action input, it returned no version instead of the latest version
> only set version when we find artifact for that version

- .github/workflows/jira-transition.yml
only attempt to transition in jira if the github issue has been mirrored to jira (example of a failure when the issue doesn't exist in jira https://github.com/dbt-labs/homebrew-dbt/runs/6033513150?check_suite_focus=true)
> tweak the jira-transition workflow

- .github/workflows/version-bump.yml
Now that all the adapters use changie, we can share this action across all adapters and core since none of it is repo-specific.
It will bump the version and generate the changie log for a release.  It will open a PR in that repo that needs to be approved.  No auto-commits allowed anymore.
This is the exact workflow we currently use in `dbt-core` just with a `workflow_call` trigger instead of a `workflow_dispatch` trigger.
> add reusable version-bump

- .github/workflows/version-bump.yml
Spark needs to install an additional dependency to it's environment. The previous version bump script in the Spark repo had this specific line
https://github.com/dbt-labs/dbt-spark/commit/5297b9225263fb33338fc54f004365ec1ad47104#diff-e8ca070981ccdc3f369851c960bec6882143a0c7afe78acd7b05e0c2b0068d72L58
> Adding spark dependency to version bump

- scripts/core-triage/graphql_queries.py
- scripts/core-triage/project.py
closes #31 
some notable things:
- see linked issue, can't `filterBy` PRs for some reason
- hit a 503 while testing, should add retry logic and whatnot 
- simply adds last 100 PRs for each repo on a schedule, should be fine
> add PRs to Core triage project automation

- scripts/core-triage/project.py
simply add those two in the list
"Refinement" in particular we want to keep an eye on in the project
> add "Refinement" and "more_information_needed" labels into triage issue automation

- .github/workflows/version-bump.yml
Description
GHA removed Homebrew from their PATH var so adding it back in.
Also did some refactoring and moving all homebrew installs to a separate step and also cleaning up newline formatting issues like we cleanup extra whitespace
See original PR in Core https://github.com/dbt-labs/dbt-core/pull/5963
> Update Version Bump to include Homebrew in PATH

- .github/workflows/replace-label.yml
resolves #35 
Made it extra generic, but defaults to change `awaiting response` to `triage` labels.
Once this is merged, we need corresponding PRs to add (modify in `dbt-core`) this workflow in adapters and any other repos we want to track
> add generic label swap action

- .github/workflows/jira-label.yml
- .github/workflows/jira-transition.yml
After some searching this was a case of use of the wrong var because in fact, `$GITHUB_STATE != $GITHUB_OUTPUT`
> github_state -> github_output

- .github/workflows/stale-bot-matrix.yml
Creating a shared stale bot Action with rules that were wanted in this issue 
https://github.com/dbt-labs/dbt-core/issues/5876
All our OSS repos can use these rules and import this Action into their repos
This is a section in the Action itself but these are the rules but can be altered if you don't like them
Stale label rules:
* waiting_response, more_information_needed -> 90 days
* good_first_issue, help_wanted -> 360 days (a year)
* tech_debt -> 720 (2 years)
* all else defaults -> 180 days (6 months)
> Creating stale bot for all repos with specific rules

- .github/workflows/jira-creation.yml
With the new env vars there's also [syntax for multiline string](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings) that we need to use when looking at labels because `${{ toJSON(github.event.issue.labels.*.name) }}` is actually a multiline string.  
This change makes it so we capture all line of the string as an array we can use as a matrix later on instead of it looking just like a plain string of a single (incorrectly formatted) label.
> capture multiline var

- scripts/core-triage/project.py
Issues opened in this repo should be (manually) assigned to @lostmygithubaccount for further triage.
> Add `dbt-server` repo to triage process

- py-package-info/action.yml
- py-package-info/main.py
We are working on the release workflow for `dbt` packages. When the workflow runs in [test mode](https://github.com/dbt-labs/dbt-release/blob/b5cc5b5f1291c3e85fddc60a3379b97936551366/.github/workflows/pypi-release.yml#L94-L110), the package will be uploaded to the [test python package index](https://packaging.python.org/en/latest/guides/using-testpypi/). So we need to update the `py-package-info` GH action to provide an ability to select package index to fetch package info. Also, the `::set-output` command will be deprecated in the future, so we need to replace it according to this guide: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
_Chagelog_:
- Add `check-test-index` input to check package info in the test …
> [`py-package-info` Action] Add ability to select package index and replace `::set-output` command

- py-package-info/action.yml
- py-package-info/main.py
This pr introduces retry logic for the `py-package-info` GH  action. This logic should help to cover the following scenarios:
- Intermittent network issues when fetching metadata from PyPI;
- Checking the availability of a new version of the package during the release process;
_Retry logic strategy_:
- Try fetching package metadata;
- If the action didn't manage to fetch package metadata - raise an exception and retry;
- If the action managed to fetch package metadata, but version validation failed - raise an exception and retry;
- If, after several attempts action didn't manage to fetch package metadata - raise an error;
- If, after several attempts, version validation is not passed  - try to use the newest version available; 
**Changelog**:
- Added `retries` input;
- …
> [`py-package-info` Action] Introduce retry logic

- .github/workflows/test-dbt-installation-main.yml
- .github/workflows/test-dbt-installation-pip.yml
This PR adds implementation for the `test-dbt-installation-pip` workflow to test dbt adapters [installation via pip](https://docs.getdbt.com/docs/get-started/pip-install).
_Changelog_:
- Added initial implementation;
- Updated workflow docs;
**Related issue**:
- #62 
**Run examples**:
- https://github.com/dbt-labs/actions/actions/runs/3957052548;
- https://github.com/dbt-labs/actions/actions/runs/3957074386
> [CI/CD] Add implementation for `test-dbt-installation-pip` workflow

- .github/workflows/test-dbt-installation-docker.yml
- .github/workflows/test-dbt-installation-homebrew.yml
- .github/workflows/test-dbt-installation-main.yml
- .github/workflows/test-dbt-installation-notify-job-statuses.yml
- .github/workflows/test-dbt-installation-pip.yml
- .github/workflows/test-dbt-installation-source.yml
- .github/workflows/test-dbt-installation-verify-test-jobs-statuses.yml
This pull request contains the implementation for the Slack notifications about failed dbt installation tests.
All workflows were adjusted to dump job statuses. These dumps are uploaded as build artifacts. Additionally, a new workflow was introduced. The main idea of this workflow is to process job statuses and generate reports. In the current implementation, the workflow downloads the artifact processes job statuses and provides statistics in the following format:
```console
Test jobs statuses: success - 0, failure - 5, cancelled - 0, undefined - 0.
```
**Changelog**:
test-dbt-installation-verify-test-jobs-statuses.yml:
- Added initial implementation;
test-dbt-installation-main.yml:
- Enabled schedule trigger;
test-dbt-installation-docker.yml:
- Added step to dump job …
> [CI/CD] Implement slack notifications for `test-dbt-installation-*` workflows

- .github/workflows/test-dbt-installation-docker.yml
- .github/workflows/test-dbt-installation-main.yml
- .github/workflows/test-dbt-installation-notify-job-statuses.yml
- .github/workflows/test-dbt-installation-pip.yml
- .github/workflows/test-dbt-installation-source.yml
During workflow runtime, we collect jobs dump to use them for notifications. The current name pattern for file names causes the files to overwrite due to name collisions. This PR changes the pattern for file names to avoid it.
**Changelog**:
- Name pattern now includes package name to avoid files overwrite;
- Changed secret for Slack;
**Run example**:
- https://github.com/dbt-labs/actions/actions/runs/4023512896
> [dbt installation] Change name pattern for job dump and replace Slack secret

- .github/workflows/test-dbt-installation-source.yml
resolves: #81 
Adds exclude parameters to installations tests for 1.0.latest branch only.
> remove python 3.9 and 3.10 from 1.0.latest source tests

- .github/workflows/cut-release-branch.yml
- .github/workflows/version-bump.yml
- .gitignore
Had to patch this in `dbt-spark`: [PR](https://github.com/dbt-labs/dbt-spark/pull/661). 
This is breaking the Version bump workflow and blocking the release. [Workflow Failed Run](https://github.com/dbt-labs/dbt-spark/actions/runs/4319432677/jobs/7538606244)
> Fixing the libsasl2 installation

- .github/workflows/jira-creation-actions.yml
- .github/workflows/jira-label-actions.yml
- .github/workflows/jira-transition-actions.yml
- .github/workflows/swap-labels.yml
jira workflows need a workflow_call trigger.  Everything that uses teh CT tag uses these workflows.
> fix missing trigger on workflows

- .github/workflows/release-branch-tests.yml
The marketplace workflow that we had been using has been abandoned so it needed to be replaced.
This centralizes the release branch testing for core and all adapters.
> centralize release branch tests

- scripts/core-triage/project.py
We renamed the core team in GitHub and this will reflect that.  The workflow has been failing for a while.
Should we add any more labels?
> fix core team name

- .github/workflows/jira-creation.yml
- .github/workflows/jira-label.yml
Resolve #50 
Resolves #102 
Fixes some issues with triggering.
1. `jira-label` fails often because it runs when a PR is opened but fails because the `jira-creation` workflow hasn't finished adding the issue so it doesn't have an issue id to work off.  `jira-creation` already syncs the labels so it's okay to skip this one if there is no issue id yet.
2. `jira-creation` fails when an issue is created with no labels.  The issue is still mirrored into Jira but the workflows ends with a failed status because the last step fails.
> fix some errors with jira actions

- .github/workflows/swap-labels.yml
Two things:
- Make the description for the action generic rather than a specific reference to the dbt Core team
- Fix a spelling mistake
> Remove reference to core team from `swap-labels.yml`

- .github/workflows/release-branch-tests.yml
[BigQuery references this action](https://github.com/dbt-labs/dbt-bigquery/blob/main/.github/workflows/release-branch-tests.yml), but needs to post the alerts to a different channel.
This change branches on the calling repository to send alerts to core if the calling repo is dbt-core, and to adapters otherwise.
> Split adapter and core alerts

- .github/workflows/open-issue-in-repo.yml
Replaces actor with PR author.  If we use the actor it will be the one that either hits the merge button or adds the `user docs` label.
Ideally the PR author can add the context needed or tag someone else in.
> Update open-issue-in-repo.yml to use PR author

- .github/workflows/open-issue-in-repo.yml
Resolves https://github.com/dbt-labs/dbt-core/issues/8439
Removes label and assignee values from issue creation.  This is due to a scoped permission issue with github workflows.   Additionally, this adds the ability to test this workflow by inputting a PR number.
For the destination repo to add labels and/or assignee, they must trigger a workflow in their own repository.
This PR is tightly tied to https://github.com/dbt-labs/dbt-core/pull/8557
> remove labels and assignees

- .github/workflows/test-dbt-installation-homebrew.yml
Homebrew installation tests are timing out because `brew upgrade` takes almost six hours 
From homebrew logs:
> Warning: You are using macOS 11.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
> use latest stable macos runner for homebrew tests

- .github/workflows/core-triage.yml
- scripts/core-triage/project.py
resolves #143 
The triage action has been failing for the past 2 months.  
Private/internal repos cause it to fail while processing.  New repos were added to the team but no added to the exclude.  This automation has only been partially working.
- Remove internal/private repos as an exclude list and replace it with logic to always exclude private repos
- Send a notification when things do fail so it doesn't fail into the void
> add private repos to excludes

- .github/workflows/core-triage.yml
resolves #149 
The failure message of the `core-triage` action has been updated to better convey the low severity of one-off failures
> Update `core-triage` failure message to better convey low severity

- py-package-info/Dockerfile
- py-package-info/main.py
We were pinned to debian 10 which is out of support and used python 3.7 when we now need 3.8. The use of this image is dubious and should be revisited, but for now bump to debian 12.
> Bump debian up to a supported version with Python >= 3.8

- .github/workflows/determine-team-membership.yml
- .github/workflows/label-community.yml
Got this error:
```
Run gh api -H "Accept: application/vnd.github+json" orgs/dbt-labs/teams/core/members > output_8394132721.json
gh api -H "Accept: application/vnd.github+json" orgs/dbt-labs/teams/core/members > output_839413[2](https://github.com/dbt-labs/dbt-core/actions/runs/8394132721/job/22990577039?pr=9803#step:3:2)721.json
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
GH_TOKEN: ***
gh: Not Found (HTTP [4](https://github.com/dbt-labs/dbt-core/actions/runs/8394132721/job/22990577039?pr=9803#step:3:4)04)
gh: This API operation needs the "repo" scope. To request it, run:  gh auth refresh -h github.com -s repo
Error: Process completed with exit code 1.
```
It's the same taken we use to release and do teh same operation so the token is not the issue.  There is no
``` …
```
> Grant contents: read scope to determine team membership

- .github/workflows/test-dbt-installation-docker.yml
- .github/workflows/test-dbt-installation-homebrew.yml
- .github/workflows/test-dbt-installation-pip.yml
- .github/workflows/test-dbt-installation-source.yml
Upload artifact requires a unique artifact name now, but we were just providing a name that was specific to the date. We failed the job status check for all but one package/method as a result. This adds the package name and a timestamp to the artifact name.
> Create a unique artifact name for nightly installation tests

- .github/workflows/release-branch-tests.yml
resolves excessive alerting
Retry GH watch action up to 3 times instead of erroring after the first failure.
> Retry `gh run watch` in `release-branch-tests` to avoid network errors

- .github/dependabot.yml
`dependabot` does not allow for multiple directories or recursion. Each directory requires an entry.
> Update dependabot to account for multiple directories

- .github/workflows/release-branch-tests.yml
resolves #171 
dbt-common is owned by the core team so the alerts need to be routed to the core team instead of falling into the adapters.  This was causing these alerts to silently fail since the adapters webhook wasn't passed in.
> fix slack alerts

- .github/workflows/open-issue-in-repo.yml
resolves #
- Add PAT as token when checking for comment
- Remove comment author since it varies by PAT used
- Removed `workflow_dispatch` options since it will never work with the PAT need
- Cleans up some comments.
> Use PAT for checking for comment

- .github/workflows/cut-release-branch.yml
- .github/workflows/test-dbt-installation-pip.yml
- .github/workflows/test-dbt-installation-source.yml
- .github/workflows/version-bump.yml
Stop running workflows with python 3.8
> we’ve dropped 3.8 so let’s remove it everywhere

- .github/workflows/release-branch-tests.yml
Make `main` optional for release branch tests to allow legacy adapter repos to continue running release branch tests on `.latest` branches while turning off this testing on `main`. This testing is replaced by the tests running in `dbt-labs/dbt-adapters`.
> Make `main` optional for release branch tests
