parse-semver/main.py
py-package-info/action.yml
py-package-info/main.py

adds logging to outputs, see https://github.com/dbt-labs/actions/runs/6025994728?check_suite_focus=true#step:3:92

add logging output

---

README.md
py-package-info/main.py

see https://docs.github.com/en/github-ae@latest/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging for more info
this adds add best practices for logging during GHA

add debug output

---

.github/workflows/jira-label.yml

This `if` statement currently is failing for me with this action and the transition action where the statement is always false. I'm wondering if we need to wrap this reference like we do with secrets

Fixing up project key ref

---

.github/workflows/jira-transition.yml

Doing the same thing as here #9

Fixing transition input reference

---

.github/workflows/jira-transition.yml

Fix naming to point to previous _job_ output instead of _step_ output

fix variable naming

---

.github/workflows/jira-creation-actions.yml
.github/workflows/jira-creation.yml
.github/workflows/jira-label.yml
.github/workflows/jira-transition.yml

resolves #44 
- Add/update versions on all jira actions
- Correct `$GITHUB_STATE` -> `$GITHUB_OUTPUT`

fix central jira actions

---

.github/workflows/test-dbt-installation-docker.yml
.github/workflows/test-dbt-installation-homebrew.yml
.github/workflows/test-dbt-installation-main.yml
.github/workflows/test-dbt-installation-pip.yml
.github/workflows/test-dbt-installation-source.yml

This PR introduces several workflows that are required to test different `dbt` installations method:
`test-dbt-installation-main`:
- Main workflow that will call reusable workflows to run integration tests for adapters;
- Workflow specification:
- _Triggers_: Schedule and Manual
`test-dbt-installation-homebrew`:
- Work flow to test [Homebrew installation](https://docs.getdbt.com/docs/get-started/homebrew-install);
- The current implementation is from [dbt-labs/homebrew-dbt](https://github.com/dbt-labs/homebrew-dbt/blob/main/.github/workflows/installation-tests.yml);
- Workflow specification:
- _Triggers_: On workflow call and Manual;
- _Inputs_: `package_name` - name of package to run test against;
- _Secrets_: `SLACK_WEBHOOK_URL` - Slack app webhook url to post …

[CI/CD] Introduce workflows to test `dbt` installations

---

.github/workflows/test-dbt-installation-docker.yml
.github/workflows/test-dbt-installation-homebrew.yml
.github/workflows/test-dbt-installation-main.yml
.github/workflows/test-dbt-installation-pip.yml
.github/workflows/test-dbt-installation-source.yml

This PR provides fixes for `dbt` installation workflows.
_Changelog_:
- Fixed workflow local paths;
- Updated permissions;
**Test runs**:
dbt Installation Tests: https://github.com/dbt-labs/actions/actions/runs/3950631342/
dbt Installation - Docker Integration Tests: https://github.com/dbt-labs/actions/actions/runs/3950626433
dbt Installation - Homebrew Integration Tests: https://github.com/dbt-labs/actions/actions/runs/3950780706
dbt Installation - pip Integration Tests: https://github.com/dbt-labs/actions/actions/runs/3950782740
dbt Installation - Source Integration Tests: https://github.com/dbt-labs/actions/actions/runs/3950784655

[CI/CD] Fix `dbt` installation workflows

---

.github/workflows/test-dbt-installation-docker.yml
.github/workflows/test-dbt-installation-main.yml

This PR adds implementation for the `test-dbt-installation-docker` workflow to test dbt adapters [installation via Docker](https://docs.getdbt.com/docs/get-started/docker-install).
_Changelog_:
`test-dbt-installation-docker`:
- Added initial implementation;
- Updated workflow docs;
`test-dbt-installation-main`:
- Added selector to provide an ability to run specific dbt installation tests;
**Related issue**:
- #62 
- dbt-labs/dbt-core/issues/5154
**Run examples**:
- https://github.com/dbt-labs/actions/actions/runs/3958917128;
- https://github.com/dbt-labs/actions/actions/runs/3958807499;
- https://github.com/dbt-labs/actions/actions/runs/3958826242;

[CI/CD] Add implementation for `test-dbt-installation-docker` workflow 

---

.github/workflows/test-dbt-installation-main.yml
.github/workflows/test-dbt-installation-source.yml

This PR adds implementation for the `test-dbt-installation-source` workflow to test dbt adapters [installation from sources](https://docs.getdbt.com/docs/get-started/source-install).
_Changelog_:
- Added initial implementation;
- Updated workflow docs;
**Related issue**:
- #62 
**Run examples**:
- https://github.com/dbt-labs/actions/actions/runs/3967169576;
- https://github.com/dbt-labs/actions/actions/runs/3967208445;

[CI/CD] Add implementation for `test-dbt-installation-source` workflow

---

.github/workflows/cut-release-branch.yaml

- Cleaned up the workflow to work in jobs for easier debugging.
- Fixed bug with PR not creating.
- Added Annotations
- Commented out the script for adapters.  I don't have capacity for this right now.  The rest of the workflow will work, that change can be done manually for now and the work will still be overall reduces for the adapters to cut new `*.latest` branches.

Cleanup cutting .latest branches

---

.github/workflows/cut-release-branch.yml

work on adapter cut-release and nightly-release update

---

.github/workflows/cut-release-branch.yml

Run bump version after change log cleanup

---

.github/workflows/cut-release-branch.yml
parse-semver/action.yml
parse-semver/main.py

calculate next version instead of using workflow input in cut-release-branch.yml

Automate next version bump in cut release

---

.github/workflows/cut-release-branch.yml

Fixes how the output is set for the alpha version so we can bump main correctly
Also fixed pre-commit failures

fix latest cutter

---

.github/workflows/changelog-existence.yml

Resolves #116 
Stop using external actions where possible.
Fix syntax errors.

Updating changelog existence check

---

.github/workflows/cut-release-branch.yml

Resolves #121 
- move creating new branch to the end
- move code quality cleanup into a single job
- minor formatting fixes

Fix pre-commit failures on PR

---

.github/dependabot.yml

resolves https://github.com/dbt-labs/dbt-core/issues/8776
No automation around GHA
Add automated checks via dependabot

add dependabot checks

---

.github/workflows/determine-team-membership.yml
.github/workflows/label-community.yml

resolves https://dbtlabs.atlassian.net/browse/OSS-3
Label PRs with `community` label when the author is outside the input team

Label community PRs

---

.github/workflows/determine-team-membership.yml
.github/workflows/label-community.yml

resolves https://dbtlabs.atlassian.net/browse/OSS-3
Fixes a permission issue so the workflow can run.  We're labeling PRs, not issues.

fix permissions on label workflows

---

.github/workflows/open-issue-in-repo.yml

resolves #162 
Use issues instead of PRs to be the source of truth for new issues we create

update workflow to use issues instead of prs

---

.github/workflows/test-dbt-installation-docker.yml
.github/workflows/test-dbt-installation-homebrew.yml
.github/workflows/test-dbt-installation-pip.yml
.github/workflows/test-dbt-installation-source.yml

Add bash as the default runner

---

.github/workflows/open-issue-in-repo.yml

resolves #
We have systems that want to trigger this behavior off of a PR instead of an issue.  This allows both event types to work.

Add support for PRs

---

.github/workflows/open-issue-in-repo.yml

We need to use the passed in PAT for everywhere we need to access repos/issues/PRs.

replace last access spot with PAT

---

.github/workflows/release-branch-tests.yml

exclude branches 1.3.latest and below

---

.github/workflows/release-branch-tests.yml
.github/workflows/test-dbt-installation-source.yml
fetch-repo-branches/Dockerfile
fetch-repo-branches/README.md

Scheduled tests are failing due to the docker image using 2 python versions.  Just use a single image container to ensure the python version isn't changing.

fix fetch-repo-branches

---

.github/workflows/cut-release-branch.yml
.github/workflows/test-dbt-installation-pip.yml
.github/workflows/test-dbt-installation-source.yml

resolves #
When quotes are missing 3.10 get converted to 3.1 in some github contexts.

Add quotations on python version

---

.github/workflows/stale-bot-matrix.yml

Don't close issues after marking them as stale.

Don't close issues after marking them as stale.

---

.github/workflows/release-branch-tests.yml

 exclude dbt-core<=1.6 from scheduled testing

---

.github/workflows/release-branch-tests.yml

Remove 1.8.latest from CI runs.

Remove 1.8.latest from CI runs
